#ifndef MZKANA_H
#define MZKANA_H

/* Generated by cbindgen — do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque engine handle returned by `mzkana_engine_create`.
 */
typedef struct MzkanaEngine MzkanaEngine;

/**
 * Result of processing a key event.
 *
 * String fields are NUL-terminated UTF-8 byte arrays.  `*_len` gives the
 * byte count **excluding** the NUL terminator, so callers can construct a
 * `std::string` with `std::string(field, field_len)`.
 */
typedef struct MzkanaResult {
  /**
   * 1 if the key event was consumed by the IME; 0 if it should be
   * forwarded to the application unchanged.
   */
  uint8_t consumed;
  /**
   * Current preedit / composition string (may be empty).
   */
  uint8_t preedit[512];
  uint32_t preedit_len;
  /**
   * Text to commit to the application (may be empty).
   */
  uint8_t commit[512];
  uint32_t commit_len;
  /**
   * If `consumed == 0`, the key name to pass through (may be empty).
   */
  uint8_t passthrough_key[64];
  uint32_t passthrough_key_len;
  /**
   * XKB keysym name of a key to forward to the application with modifier synthesis.
   * Non-empty only when a modifier+key token was not consumed by Mozc.
   * The C++ layer should call ic->forwardKey() with this key and `forward_modifiers`.
   */
  uint8_t forward_key[64];
  uint32_t forward_key_len;
  /**
   * Modifier bitmask for `forward_key`: bit0=Shift, bit1=Ctrl, bit2=Alt, bit3=Super.
   */
  uint8_t forward_modifiers;
} MzkanaResult;

/**
 * One candidate entry. `value` / `annotation` are NUL-terminated UTF-8 borrowed
 * from the engine; `annotation` is NULL when absent. `*_len` excludes the NUL.
 */
typedef struct MzkanaCandidate {
  const uint8_t *value;
  uint32_t value_len;
  const uint8_t *annotation;
  uint32_t annotation_len;
  /**
   * Mozc-internal candidate id (for SELECT_CANDIDATE), or -1 when the candidate
   * has no id and therefore cannot be selected by id.
   */
  int32_t id;
} MzkanaCandidate;

/**
 * Create a new engine.
 *
 * `config_path`  — NUL-terminated UTF-8 path to the layout TOML file.
 * `socket_path`  — NUL-terminated UTF-8 path to the Mozc UDS socket, or
 *                  NULL to use the default (`~/.mozc/session.sock`).
 *
 * Returns NULL on failure (logs the reason to stderr).
 *
 * # Safety
 * `config_path` must be a valid NUL-terminated C string.
 * `socket_path` must be a valid NUL-terminated C string or NULL.
 */
struct MzkanaEngine *mzkana_engine_create(const char *config_path, const char *socket_path);

/**
 * Destroy an engine previously created with `mzkana_engine_create`.
 * Passing NULL is safe and does nothing.
 *
 * # Safety
 * `engine` must be a pointer returned by `mzkana_engine_create`, or NULL.
 * After this call the pointer is invalid and must not be used again.
 */
void mzkana_engine_destroy(struct MzkanaEngine *engine);

/**
 * Process a key-down event.
 *
 * `key_name` — XKB keysym name at level 0, e.g. `"a"`, `"comma"`, `"space"`,
 *              `"henkan"`.
 * `shift`    — 1 if the Shift key is held, 0 otherwise.
 *
 * # Safety
 * `engine` must be a valid non-null pointer returned by `mzkana_engine_create`.
 * `key_name` must be a valid NUL-terminated C string.
 */
struct MzkanaResult mzkana_engine_key_down(struct MzkanaEngine *engine,
                                           const char *key_name,
                                           uint8_t shift);

/**
 * Process a key-up event.
 *
 * # Safety
 * `engine` must be a valid non-null pointer returned by `mzkana_engine_create`.
 * `key_name` must be a valid NUL-terminated C string.
 */
struct MzkanaResult mzkana_engine_key_up(struct MzkanaEngine *engine, const char *key_name);

/**
 * Advance internal timers.  Call from an fcitx5 timer callback with the
 * chord-window interval (e.g. every 10 ms while preedit is active).
 *
 * # Safety
 * `engine` must be a valid non-null pointer returned by `mzkana_engine_create`.
 */
struct MzkanaResult mzkana_engine_tick(struct MzkanaEngine *engine);

/**
 * Select and commit the candidate with the given Mozc-internal `candidate_id`
 * (e.g. when the user presses a number key or clicks a candidate). The returned
 * `MzkanaResult.commit` holds the committed text; the candidate window is closed.
 *
 * # Safety
 * `engine` must be a valid non-null pointer returned by `mzkana_engine_create`.
 */
struct MzkanaResult mzkana_engine_select_candidate(struct MzkanaEngine *engine,
                                                   int32_t candidate_id);

/**
 * Reset engine state (call on focus loss or IM deactivation).
 * Any pending preedit is discarded.
 *
 * # Safety
 * `engine` must be a valid pointer returned by `mzkana_engine_create`, or NULL.
 */
void mzkana_engine_reset(struct MzkanaEngine *engine);

/**
 * Handle focus loss, honoring the layout's `on_focus_change` setting
 * (preserve / reset). Call from the C++ `deactivate` handler.
 *
 * Returns 1 if the composition state was preserved (caller should NOT clear
 * preedit), 0 if it was reset (caller should clear preedit).
 *
 * # Safety
 * `engine` must be a valid pointer returned by `mzkana_engine_create`, or NULL.
 */
uint8_t mzkana_engine_focus_out(struct MzkanaEngine *engine);

/**
 * `sensitive_field_behavior` setting (0 = passthrough, 1 = buffer).
 * Returns 0 for a NULL engine.
 *
 * # Safety
 * `engine` must be a valid pointer returned by `mzkana_engine_create`, or NULL.
 */
int32_t mzkana_engine_sensitive_field_behavior(const struct MzkanaEngine *engine);

/**
 * `preedit_fallback` setting (0 = client, 1 = panel, 2 = buffer, 3 = auto).
 * Returns 1 (panel) for a NULL engine.
 *
 * # Safety
 * `engine` must be a valid pointer returned by `mzkana_engine_create`, or NULL.
 */
int32_t mzkana_engine_preedit_fallback(const struct MzkanaEngine *engine);

/**
 * Check whether the config file changed and reload it if so.
 *
 * Returns 1 if the config was reloaded, 0 otherwise.
 * Call this periodically (e.g. once per key event or from a timer).
 *
 * # Safety
 * `engine` must be a valid pointer returned by `mzkana_engine_create`, or NULL.
 */
uint8_t mzkana_engine_check_reload(struct MzkanaEngine *engine);

/**
 * Returns 1 if the Mozc conversion engine is connected, 0 otherwise.
 *
 * Use this to determine the current engine state for UI display (e.g. status
 * area labels).
 *
 * # Safety
 * `engine` must be a valid pointer returned by `mzkana_engine_create`, or NULL.
 */
uint8_t mzkana_engine_mozc_available(const struct MzkanaEngine *engine);

/**
 * Number of candidates in the most recent Mozc output (current page).
 *
 * # Safety
 * `engine` must be a valid pointer returned by `mzkana_engine_create`, or NULL.
 */
uint32_t mzkana_engine_candidate_count(const struct MzkanaEngine *engine);

/**
 * Fetch the `i`-th candidate. Returns an all-NULL/zero struct if `engine` is
 * NULL or `i` is out of range. Strings are NUL-terminated and engine-owned;
 * valid only until the next key event.
 *
 * # Safety
 * `engine` must be a valid pointer returned by `mzkana_engine_create`, or NULL.
 */
struct MzkanaCandidate mzkana_engine_candidate(const struct MzkanaEngine *engine, uint32_t i);

/**
 * Focused candidate index during conversion, or -1 for a suggestion window /
 * no window / NULL engine.
 *
 * # Safety
 * `engine` must be a valid pointer returned by `mzkana_engine_create`, or NULL.
 */
int32_t mzkana_engine_focused_index(const struct MzkanaEngine *engine);

#endif  /* MZKANA_H */
