#ifndef MZKANA_H
#define MZKANA_H

/* Generated by cbindgen — do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque engine handle returned by `mzkana_engine_create`.
 */
typedef struct MzkanaEngine MzkanaEngine;

/**
 * Result of processing a key event.
 *
 * String fields are NUL-terminated UTF-8 byte arrays.  `*_len` gives the
 * byte count **excluding** the NUL terminator, so callers can construct a
 * `std::string` with `std::string(field, field_len)`.
 */
typedef struct MzkanaResult {
  /**
   * 1 if the key event was consumed by the IME; 0 if it should be
   * forwarded to the application unchanged.
   */
  uint8_t consumed;
  /**
   * Current preedit / composition string (may be empty).
   */
  uint8_t preedit[512];
  uint32_t preedit_len;
  /**
   * Text to commit to the application (may be empty).
   */
  uint8_t commit[512];
  uint32_t commit_len;
  /**
   * If `consumed == 0`, the key name to pass through (may be empty).
   */
  uint8_t passthrough_key[64];
  uint32_t passthrough_key_len;
  /**
   * XKB keysym name of a key to forward to the application with modifier synthesis.
   * Non-empty only when a modifier+key token was not consumed by Mozc.
   * The C++ layer should call ic->forwardKey() with this key and `forward_modifiers`.
   */
  uint8_t forward_key[64];
  uint32_t forward_key_len;
  /**
   * Modifier bitmask for `forward_key`: bit0=Shift, bit1=Ctrl, bit2=Alt, bit3=Super.
   */
  uint8_t forward_modifiers;
} MzkanaResult;

/**
 * Create a new engine.
 *
 * `config_path`  — NUL-terminated UTF-8 path to the layout TOML file.
 * `socket_path`  — NUL-terminated UTF-8 path to the Mozc UDS socket, or
 *                  NULL to use the default (`~/.mozc/session.sock`).
 *
 * Returns NULL on failure (logs the reason to stderr).
 *
 * # Safety
 * `config_path` must be a valid NUL-terminated C string.
 * `socket_path` must be a valid NUL-terminated C string or NULL.
 */
struct MzkanaEngine *mzkana_engine_create(const char *config_path, const char *socket_path);

/**
 * Destroy an engine previously created with `mzkana_engine_create`.
 * Passing NULL is safe and does nothing.
 *
 * # Safety
 * `engine` must be a pointer returned by `mzkana_engine_create`, or NULL.
 * After this call the pointer is invalid and must not be used again.
 */
void mzkana_engine_destroy(struct MzkanaEngine *engine);

/**
 * Process a key-down event.
 *
 * `key_name` — XKB keysym name at level 0, e.g. `"a"`, `"comma"`, `"space"`,
 *              `"henkan"`.
 * `shift`    — 1 if the Shift key is held, 0 otherwise.
 *
 * # Safety
 * `engine` must be a valid non-null pointer returned by `mzkana_engine_create`.
 * `key_name` must be a valid NUL-terminated C string.
 */
struct MzkanaResult mzkana_engine_key_down(struct MzkanaEngine *engine,
                                           const char *key_name,
                                           uint8_t shift);

/**
 * Process a key-up event.
 *
 * # Safety
 * `engine` must be a valid non-null pointer returned by `mzkana_engine_create`.
 * `key_name` must be a valid NUL-terminated C string.
 */
struct MzkanaResult mzkana_engine_key_up(struct MzkanaEngine *engine, const char *key_name);

/**
 * Advance internal timers.  Call from an fcitx5 timer callback with the
 * chord-window interval (e.g. every 10 ms while preedit is active).
 *
 * # Safety
 * `engine` must be a valid non-null pointer returned by `mzkana_engine_create`.
 */
struct MzkanaResult mzkana_engine_tick(struct MzkanaEngine *engine);

/**
 * Reset engine state (call on focus loss or IM deactivation).
 * Any pending preedit is discarded.
 *
 * # Safety
 * `engine` must be a valid pointer returned by `mzkana_engine_create`, or NULL.
 */
void mzkana_engine_reset(struct MzkanaEngine *engine);

/**
 * Check whether the config file changed and reload it if so.
 *
 * Returns 1 if the config was reloaded, 0 otherwise.
 * Call this periodically (e.g. once per key event or from a timer).
 *
 * # Safety
 * `engine` must be a valid pointer returned by `mzkana_engine_create`, or NULL.
 */
uint8_t mzkana_engine_check_reload(struct MzkanaEngine *engine);

#endif  /* MZKANA_H */
